event trigger

diff --git a/.github/workflows/auto-update.yml b/.github/workflows/auto-update.yml
--- a/.github/workflows/auto-update.yml
+++ b/.github/workflows/auto-update.yml
@@ -1,37 +1,37 @@
-# name: auto-update
-# on:
-#   push: {}
-# jobs:
+name: auto-update
+on:
+  push: {}
+jobs:
   
-#   validate-tag-if-present:
-#     runs-on: ubuntu-latest
+  validate-tag-if-present:
+    runs-on: ubuntu-latest
 
-#     steps:
-#       - name: TAGGED, Validate that the tag is in the correct format
+    steps:
+      - name: TAGGED, Validate that the tag is in the correct format
         
-#         run: |
-#           echo "The GITHUB_REF: $GITHUB_REF"
-#           #First check to see if the release is a tag
-#           if [[ $GITHUB_REF =~ refs/tags/* ]]; then
-#             #Yes, this is a tag, so we need to test to make sure that the tag
-#             #is in the correct format (like v1.10.20)
-#             if [[ $GITHUB_REF =~ refs/tags/v[0-9]+.[0-9]+.[0-9]+ ]]; then
-#               echo "PASS: Tagged release with good format"
-#               exit 0
-#             else
-#               echo "FAIL: Tagged release with bad format"
-#               exit 1
-#             fi
-#           else
-#           echo "PASS: Not a tagged release"
-#           exit 0
-#           fi                          
-#   autoupdate:
-#     name: autoupdate
-#     runs-on: ubuntu-latest
-#     steps:
-#       - uses: docker://chinthakagodawita/autoupdate-action:v1
-#         env:
-#           GITHUB_TOKEN: "${{ secrets.SECURITY_CONTENT_ADMIN_TASKS }}"
-#           DRY_RUN: "false"
-#           MERGE_MSG: "Branch was auto-updated."
+        run: |
+          echo "The GITHUB_REF: $GITHUB_REF"
+          #First check to see if the release is a tag
+          if [[ $GITHUB_REF =~ refs/tags/* ]]; then
+            #Yes, this is a tag, so we need to test to make sure that the tag
+            #is in the correct format (like v1.10.20)
+            if [[ $GITHUB_REF =~ refs/tags/v[0-9]+.[0-9]+.[0-9]+ ]]; then
+              echo "PASS: Tagged release with good format"
+              exit 0
+            else
+              echo "FAIL: Tagged release with bad format"
+              exit 1
+            fi
+          else
+          echo "PASS: Not a tagged release"
+          exit 0
+          fi                          
+  autoupdate:
+    name: autoupdate
+    runs-on: ubuntu-latest
+    steps:
+      - uses: docker://chinthakagodawita/autoupdate-action:v1
+        env:
+          GITHUB_TOKEN: "${{ secrets.SECURITY_CONTENT_ADMIN_TASKS }}"
+          DRY_RUN: "false"
+          MERGE_MSG: "Branch was auto-updated."
