testing failures

diff --git a/.github/workflows/unit-testing.yml b/.github/workflows/unit-testing.yml
--- a/.github/workflows/unit-testing.yml
+++ b/.github/workflows/unit-testing.yml
@@ -6,31 +6,7 @@ on:
   schedule:
     - cron: "44 4 * * *"
 jobs:
-  # validate-tag-if-present:
-  #   runs-on: ubuntu-latest
-
-  #   steps:
-  #     - name: TAGGED, Validate that the tag is in the correct format
-        
-  #       run: |
-  #         echo "The GITHUB_REF: $GITHUB_REF"
-  #         #First check to see if the release is a tag
-  #         if [[ $GITHUB_REF =~ refs/tags/* ]]; then
-  #           #Yes, this is a tag, so we need to test to make sure that the tag
-  #           #is in the correct format (like v1.10.20)
-  #           if [[ $GITHUB_REF =~ refs/tags/v[0-9]+.[0-9]+.[0-9]+ ]]; then
-  #             echo "PASS: Tagged release with good format"
-  #             exit 0
-  #           else
-  #             echo "FAIL: Tagged release with bad format"
-  #             exit 1
-  #           fi
-  #         else
-  #         echo "PASS: Not a tagged release"
-  #         exit 0
-  #         fi                    
-  
-  docker-unit-testing-setup:
+  contentctl-unit-testing-setup:
     runs-on: ubuntu-latest
     if: "!contains(github.ref, 'refs/tags/')" #don't run on tags - future steps won't run either since they depend on this job
     # needs: [validate-tag-if-present, quit-for-dependabot]
@@ -68,8 +44,32 @@ jobs:
         
         - name: Run ContentCTL test for changes against develop
           run: |
-            git status
-            git pull
-            source .venv/bin/activate
-            git checkout unit-testing
-            contentctl test --post-test-behavior never_pause mode:changes --mode.target-branch develop
+            cat summary.xml
+            # git status
+            # git pull
+            # source .venv/bin/activate
+            # git checkout unit-testing
+            # contentctl test --post-test-behavior never_pause mode:changes --mode.target-branch develop
+
+  summarize-test-results:
+    needs: contentctl-unit-testing-setup
+    runs-on: ubuntu-latest
+    if: "!contains(github.ref, 'refs/tags/')" #don't run on tags - future steps won't run either since they depend on this job
+    # needs: [validate-tag-if-present, quit-for-dependabot]
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Install dependencies
+        run: sudo apt-get install -y jq
+
+      - name: Check Test Summary
+        run: |
+          total_fail=$(cat security_content/test_results/summary.yml | yq e '.summary.total_fail' -)
+          if [ "$total_fail" != "0" ]; then
+            echo "CI Failure: There are failed tests."
+            cat security_content/test_results/summary.yml | yq e '.summary' -
+            exit 1
+          else
+            echo "CI Success: No failed tests."
+          fi
